# Generated by Django 5.2.11 on 2026-02-27 18:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customer_username_and_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSignupApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[6-9]\\d{9}$', 'Invalid phone number')])),
                ('shop_name', models.CharField(max_length=200)),
                ('shop_address', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_signup_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payment_tra_custome_4eb453_idx',
            old_name='payment_tra_custome_779457_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payment_tra_transac_2bf6c8_idx',
            old_name='payment_tra_transac_28f9b9_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptiondelivery',
            new_name='subscriptio_custome_04c071_idx',
            old_name='api_subscrip_customer_3104e8_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptiondelivery',
            new_name='subscriptio_schedul_63583e_idx',
            old_name='api_subscrip_schedule_6f1a43_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[6-9]\\d{9}$', 'Invalid phone number')]),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('cod', 'Cash On Delivery')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='adminsignupapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to='api.admin'),
        ),
        migrations.AddIndex(
            model_name='adminsignupapplication',
            index=models.Index(fields=['status', 'created_at'], name='admin_signu_status_5ecf28_idx'),
        ),
    ]
