# Generated by Django 4.2.10 on 2026-03-07 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_adminsignupapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('system', 'System'), ('warning', 'Warning'), ('payment', 'Payment'), ('order', 'Order')], default='system', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.product')),
            ],
            options={
                'db_table': 'user_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='user_notifi_custome_0bdcc5_idx'), models.Index(fields=['customer', 'is_read'], name='user_notifi_custome_c59bf3_idx')],
            },
        ),
    ]
