"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config as env_config, Csv
from corsheaders.defaults import default_headers
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_config('DJANGO_SECRET_KEY', default='django-insecure-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_config('DJANGO_DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = env_config(
    'DJANGO_ALLOWED_HOSTS',
    default='localhost,127.0.0.1',
    cast=Csv()
)
RENDER_EXTERNAL_HOSTNAME = env_config('RENDER_EXTERNAL_HOSTNAME', default='').strip()
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS = list(ALLOWED_HOSTS) + [RENDER_EXTERNAL_HOSTNAME]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', 
    'django_filters',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# Production: prefer DATABASE_URL (Supabase / Postgres)
# Local fallback: SQL Server settings below remain supported for current development setup.
DATABASE_URL = env_config('DATABASE_URL', default='')
DATABASE_SSL_REQUIRE = env_config('DATABASE_SSL_REQUIRE', default=not DEBUG, cast=bool)

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=env_config('DATABASE_CONN_MAX_AGE', default=600, cast=int),
            ssl_require=DATABASE_SSL_REQUIRE,
        )
    }
else:
    DB_TRUSTED_CONNECTION = env_config('DB_TRUSTED_CONNECTION', default=True, cast=bool)
    DB_OPTIONS = {
        'driver': env_config('DB_ODBC_DRIVER', default='ODBC Driver 17 for SQL Server'),
    }
    if DB_TRUSTED_CONNECTION:
        DB_OPTIONS['Trusted_Connection'] = 'yes'

    DATABASES = {
        'default': {
            'ENGINE': 'mssql',
            'NAME': env_config('DB_NAME', default='milkMan'),
            'USER': env_config('DB_USER', default=''),
            'PASSWORD': env_config('DB_PASSWORD', default=''),
            'HOST': env_config('DB_HOST', default='localhost'),
            'PORT': env_config('DB_PORT', default=''),
            'OPTIONS': DB_OPTIONS,
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = env_config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001',
    cast=Csv()
)

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-developer-token',
    'x-auth-token',
]

# Dev convenience: allow any localhost port (safe for local dev only).
DEV_ALLOW_ALL_LOCALHOST_ORIGINS = env_config('DEV_ALLOW_ALL_LOCALHOST_ORIGINS', default=True, cast=bool)
if DEBUG and DEV_ALLOW_ALL_LOCALHOST_ORIGINS:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://localhost(:\d+)?$",
        r"^http://127\.0\.0\.1(:\d+)?$",
    ]

# Required when using session auth from a separate frontend domain in production.
CSRF_TRUSTED_ORIGINS = env_config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001',
    cast=Csv()
)
if DEBUG and DEV_ALLOW_ALL_LOCALHOST_ORIGINS:
    CSRF_TRUSTED_ORIGINS = list(set(list(CSRF_TRUSTED_ORIGINS) + ['http://localhost', 'http://127.0.0.1']))

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TRUST_PROXY_SSL_HEADER = env_config('TRUST_PROXY_SSL_HEADER', default=not DEBUG, cast=bool)
if TRUST_PROXY_SSL_HEADER:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = env_config('USE_X_FORWARDED_HOST', default=TRUST_PROXY_SSL_HEADER, cast=bool)
SECURE_SSL_REDIRECT = env_config('SECURE_SSL_REDIRECT', default=False, cast=bool)

# Developer review / notifications
DEVELOPER_ALLOWED_IPS = env_config(
    'DEVELOPER_ALLOWED_IPS',
    default='127.0.0.1,::1',
    cast=Csv()
)
DEVELOPER_TRUST_X_FORWARDED_FOR = env_config('DEVELOPER_TRUST_X_FORWARDED_FOR', default=False, cast=bool)

DEVELOPER_EMAILS = env_config(
    'DEVELOPER_EMAILS',
    default='',
    cast=Csv()
)
DEVELOPER_TOKEN_MAX_AGE_SECONDS = env_config('DEVELOPER_TOKEN_MAX_AGE_SECONDS', default=60 * 60 * 12, cast=int)

# Email (defaults to console for dev)
EMAIL_BACKEND = env_config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend'
)
DEFAULT_FROM_EMAIL = env_config('DEFAULT_FROM_EMAIL', default='no-reply@milkman.local')

EMAIL_HOST = env_config('EMAIL_HOST', default='')
EMAIL_PORT = env_config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = env_config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = env_config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env_config('EMAIL_HOST_PASSWORD', default='')
EMAIL_TIMEOUT = env_config('EMAIL_TIMEOUT', default=15, cast=int)

# Session security
# Default behavior: do NOT persist login across browser restarts (prevents "last user is still logged in").
SESSION_EXPIRE_AT_BROWSER_CLOSE = env_config('SESSION_EXPIRE_AT_BROWSER_CLOSE', default=True, cast=bool)
SESSION_COOKIE_AGE = env_config('SESSION_COOKIE_AGE', default=60 * 60 * 6, cast=int)  # 6 hours
SESSION_SAVE_EVERY_REQUEST = env_config('SESSION_SAVE_EVERY_REQUEST', default=True, cast=bool)
SESSION_COOKIE_SECURE = env_config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = env_config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)
SESSION_COOKIE_SAMESITE = env_config('SESSION_COOKIE_SAMESITE', default='Lax' if DEBUG else 'None')
CSRF_COOKIE_SAMESITE = env_config('CSRF_COOKIE_SAMESITE', default='Lax' if DEBUG else 'None')
ADMIN_MAX_FAILED_LOGIN_ATTEMPTS = env_config('ADMIN_MAX_FAILED_LOGIN_ATTEMPTS', default=5, cast=int)
ADMIN_LOCKOUT_MINUTES = env_config('ADMIN_LOCKOUT_MINUTES', default=30, cast=int)
AUTH_TOKEN_MAX_AGE_SECONDS = env_config('AUTH_TOKEN_MAX_AGE_SECONDS', default=60 * 60 * 24 * 7, cast=int)

# Dev only: return OTP in API responses (for testing without SMS/email providers).
DEV_RETURN_OTPS = env_config('DEV_RETURN_OTPS', default=False, cast=bool)

# SMS (default: console in DEBUG via _send_sms_safe)
SMS_BACKEND = env_config('SMS_BACKEND', default='console')  # 'console' | 'twilio'
TWILIO_ACCOUNT_SID = env_config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = env_config('TWILIO_AUTH_TOKEN', default='')
TWILIO_FROM_NUMBER = env_config('TWILIO_FROM_NUMBER', default='')  # e.g. +12025550123

# Apply SQL Server 2025 version detection patch only for SQL Server deployments.
if DATABASES['default']['ENGINE'] == 'mssql':
    try:
        from .sql_server_patch import patch_sql_server_version
        patch_sql_server_version()
    except Exception as e:
        import sys
        print(f"Warning: Could not apply SQL Server patch: {e}", file=sys.stderr)
